<?php

/**
 * Implementation of hook_menu()
 */
function prestataires_promos_menu() {
	$items = array();

	$items['admin/prestataires-promo/autocomplete/%'] = array(// % = node type (pourquoi ?)
			'title' => "",
			'type' => MENU_CALLBACK,
			'page callback' => 'prestataires_promo_node_form_autocomplete',
			'page arguments' => array(3, 4),
			'access callback' => 'prestataires_promo_user_has_role',
			'access arguments' => array(array('webmaster', 'administrator')),
	);

	return $items;

}

function prestataires_promos_form_bon_plan_node_form_alter(&$form, &$form_state) {

	global $user;

	if(prestataires_promo_user_has_role('prestataire') || prestataires_promo_user_has_role('developpeur')) {

        $results = db_query(
            "SELECT p.nid, n.title FROM {prestataires} AS p
	        LEFT JOIN {node} AS n ON n.nid=p.nid
	        WHERE p.uid=?
	        AND n.nid IS NOT NULL
	        ORDER BY n.title ASC",
            array(
                    $user->uid,
            )
		);

        $options = array();

        while($row = $results->fetchObject()) {
            $options[$row->nid] = $row->title;
        }

        $form['field_fiche_detaillee'][LANGUAGE_NONE][0]['target_id']['#type'] = 'select';
        $form['field_fiche_detaillee'][LANGUAGE_NONE][0]['target_id']['#options'] = $options;
        $form['field_fiche_detaillee'][LANGUAGE_NONE][0]['target_id']['#default_value'] = $form['field_fiche_detaillee'][LANGUAGE_NONE][0]['target_id']['#entity']->field_fiche_detaillee[LANGUAGE_NONE][0]['target_id'];
        $form['field_fiche_detaillee'][LANGUAGE_NONE][0]['target_id']['#size'] = 1;
        $form['field_fiche_detaillee'][LANGUAGE_NONE][0]['target_id']['#element_validate'] = array();

    } else {
        $form['field_fiche_detaillee'][LANGUAGE_NONE][0]['target_id']['#autocomplete_path'] = 'admin/prestataires-promo/autocomplete/bon-plan';
    }
}

function prestataires_promo_node_form_autocomplete($content_type, $value) {

    $output = array();

	if (strlen($value)>2) {

		$results = db_query(
            "SELECT * FROM {node}
	        WHERE title LIKE ?
	        ORDER BY title ASC",
				array(
                    '%' . $value . '%'
				)
		);
	} else {
        drupal_json_output($output);
        return;
    }

	while($row = $results->fetchObject()) {
		$key = $row->title . " [" . strtoupper($row->language) . "]" . ' (' . $row->nid . ')';
		// Strip things like starting/trailing white spaces, line breaks and tags.
		$key = preg_replace('/\s\s+/', ' ', str_replace("\n", '', trim(decode_entities(strip_tags($key)))));
		// Names containing commas or quotes must be wrapped in quotes.
		if (strpos($key, ',') !== FALSE || strpos($key, '"') !== FALSE) {
			$key = '"' . str_replace('"', '""', $key) . '"';
		}
		$output[$key] = '<div class="reference-autocomplete">' . $row->title . " [" . strtoupper($row->language) . "]" . '</div>';
	}

	drupal_json_output($output);
}

/***
 * MISCELLANEOUS
 */

function prestataires_promo_user_has_role($role, $user = NULL) {
  if (!is_object($user)) {
    global $user;
  }

  if (is_array($user->roles) && count(array_intersect((array)$role, array_values($user->roles)))) {
    return TRUE;
  }

  return FALSE;
}